const { app, BrowserWindow, dialog, ipcMain, clipboard, safeStorage, Tray, Menu, nativeImage, Notification, powerMonitor } = require('electron');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { pathToFileURL } = require('url');
const { createStore } = require('./core/store');
const { createUsageService } = require('./core/usage');
const { createProjectService } = require('./core/projects');
const { createConnectionService } = require('./core/connection');

const PORT=47820;
let mainWindow=null,tray=null,isQuitting=false,mcpRuntime=null,connection=null;
const gotLock=app.requestSingleInstanceLock();if(!gotLock)app.quit();
const asset=name=>path.join(__dirname,'assets',name);
const store=createStore(app,PORT);
function send(channel,value){if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send(channel,value)}
function notifyActivity(entry){send('activity:changed',entry);const s=store.read();if(!s.settings.activityNotifications||!entry.ok||!['write','manage','task','git'].includes(entry.category))return;if(mainWindow&&!mainWindow.isDestroyed()&&mainWindow.isVisible()&&mainWindow.isFocused())return;try{if(Notification.isSupported())new Notification({title:'ChatGPT vừa thao tác dự án',body:`${entry.project||'Dự án'}${entry.target?` · ${entry.target}`:''}`,icon:fs.existsSync(asset('icon.png'))?asset('icon.png'):undefined}).show()}catch{}}
const usage=createUsageService(store,{onActivity:notifyActivity,onReset:()=>send('activity:reset')});
const projects=createProjectService(store,{onIndexChanged:value=>send('index:changed',value),recordActivity:usage.record});
async function ensureMcpServer(){if(mcpRuntime)return mcpRuntime;const s=store.ensure();const {startMcpHttpServer}=await import(pathToFileURL(path.join(__dirname,'mcp-server.mjs')).href);mcpRuntime=await startMcpHttpServer({port:PORT,token:s.connection.token,api:projects.toolApi});return mcpRuntime}
async function resetMcpServer(){if(mcpRuntime){try{await mcpRuntime.close()}catch{}mcpRuntime=null}}
function connectionChanged(value){send('connection:changed',value);updateTrayMenu()}
connection=createConnectionService({app,safeStorage,store,port:PORT,ensureMcpServer,resetMcpServer,getMcpRuntime:()=>mcpRuntime,onChanged:connectionChanged});
function applyLogin(enabled){try{const options={openAtLogin:!!enabled};if(process.platform==='win32'&&app.isPackaged&&enabled)options.args=['--background'];app.setLoginItemSettings(options)}catch{}}
function saveSettings(incoming={}){const s=store.read();for(const k of ['closeToTray','launchAtLogin','activityNotifications','autoReconnect'])if(typeof incoming[k]==='boolean')s.settings[k]=incoming[k];if(incoming.healthIntervalSec!=null)s.settings.healthIntervalSec=Math.min(120,Math.max(15,Number(incoming.healthIntervalSec)||30));store.write(s);applyLogin(s.settings.launchAtLogin);connection.restartWatchdog();updateTrayMenu();return store.settings(s)}
function showWindow(){if(!mainWindow||mainWindow.isDestroyed())createWindow(true);mainWindow.show();if(mainWindow.isMinimized())mainWindow.restore();mainWindow.focus()}
function updateTrayMenu(){if(!tray||!connection)return;const snap=connection.snapshot(),label=snap.status==='connected'?'Đã kết nối ChatGPT':snap.status==='reconnecting'?'Đang tự kết nối lại':snap.status==='offline'?'Mất kết nối':'Chưa kết nối';tray.setContextMenu(Menu.buildFromTemplate([{label,enabled:false},{type:'separator'},{label:'Mở ChatCode Cá Nhân',click:showWindow},{label:'Sao chép URL MCP',enabled:!!snap.connectionUrl,click:()=>snap.connectionUrl&&clipboard.writeText(snap.connectionUrl)},{label:'Kết nối lại ngay',click:()=>connection.start().catch(()=>{})},{type:'separator'},{label:'Thoát hoàn toàn',click:()=>{isQuitting=true;app.quit()}}]));tray.setToolTip(`ChatCode Cá Nhân · ${label}`)}
function createTray(){if(tray)return;const icon=fs.existsSync(asset('icon.png'))?nativeImage.createFromPath(asset('icon.png')).resize({width:24,height:24}):nativeImage.createEmpty();tray=new Tray(icon);tray.on('double-click',showWindow);tray.on('click',()=>{if(!mainWindow||mainWindow.isDestroyed()||!mainWindow.isVisible())showWindow()});updateTrayMenu()}
function createWindow(showInitially=true){mainWindow=new BrowserWindow({width:1480,height:930,minWidth:1100,minHeight:720,show:false,backgroundColor:'#f5f7fa',title:'ChatCode Cá Nhân',icon:fs.existsSync(asset('icon.png'))?asset('icon.png'):undefined,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});mainWindow.setMenuBarVisibility(false);mainWindow.loadFile(path.join(__dirname,'renderer','index.html'));mainWindow.on('close',e=>{if(isQuitting)return;if(store.read().settings.closeToTray){e.preventDefault();mainWindow.hide()}});mainWindow.on('closed',()=>{mainWindow=null});if(showInitially)mainWindow.once('ready-to-show',()=>mainWindow?.show())}
function updateProject(incoming){const s=store.read(),i=s.projects.findIndex(p=>p.id===incoming.id);if(i<0)throw new Error('Không tìm thấy dự án.');s.projects[i]={...s.projects[i],name:String(incoming.name||s.projects[i].name),permissions:{...s.projects[i].permissions,...(incoming.permissions||{})}};store.write(s);return s.projects[i]}
function applyPreset(id,preset){const presets={readonly:{write:false,manageFiles:false,tasks:false,gitWrite:false},development:{write:true,manageFiles:true,tasks:true,gitWrite:false},full:{write:true,manageFiles:true,tasks:true,gitWrite:true}},s=store.read(),i=s.projects.findIndex(p=>p.id===id);if(i<0)throw new Error('Không tìm thấy dự án.');if(!presets[preset])throw new Error('Preset không hợp lệ.');s.projects[i].permissions=presets[preset];store.write(s);return s.projects[i]}
ipcMain.handle('projects:list',()=>store.read().projects);
ipcMain.handle('projects:add',async()=>{const pick=await dialog.showOpenDialog(mainWindow,{title:'Chọn thư mục dự án',properties:['openDirectory']});if(pick.canceled||!pick.filePaths[0])return null;const s=store.read(),root=path.resolve(pick.filePaths[0]),existing=s.projects.find(p=>path.resolve(p.root)===root);if(existing)return existing;const project={id:crypto.randomUUID(),name:path.basename(root)||root,root,permissions:{write:false,manageFiles:false,tasks:false,gitWrite:false}};s.projects.push(project);store.write(s);projects.watch(project);projects.reindex(project.id).catch(()=>{});return project});
ipcMain.handle('projects:update',(_,incoming)=>updateProject(incoming));ipcMain.handle('projects:preset',(_,id,preset)=>applyPreset(id,preset));ipcMain.handle('projects:remove',(_,id)=>{const s=store.read(),before=s.projects.length;s.projects=s.projects.filter(p=>p.id!==id);if(s.projects.length===before)throw new Error('Không tìm thấy dự án.');store.write(s);projects.cleanup(id);return true});ipcMain.handle('projects:index-status',(_,id)=>projects.status(id));ipcMain.handle('projects:reindex',(_,id)=>projects.reindex(id));
ipcMain.handle('files:list',(_,id)=>projects.toolApi.listFiles(id));ipcMain.handle('files:read',async(_,id,rel)=>(await projects.toolApi.readFile(id,rel)).content);ipcMain.handle('files:search',(_,id,q)=>projects.toolApi.search(id,q));ipcMain.handle('tasks:run',(_,id,c)=>projects.toolApi.runTask(id,c));ipcMain.handle('git:status',(_,id)=>projects.toolApi.gitStatus(id));ipcMain.handle('git:diff',(_,id)=>projects.toolApi.gitDiff(id,false));
ipcMain.handle('connection:status',()=>connection.snapshot());ipcMain.handle('connection:config',()=>store.connectionConfig());ipcMain.handle('connection:save-config',(_,c)=>connection.saveConfig(c));ipcMain.handle('connection:clear-token',()=>connection.clearToken());ipcMain.handle('connection:start',()=>connection.start());ipcMain.handle('connection:stop',()=>connection.stop({intentional:true}));ipcMain.handle('connection:diagnose',()=>connection.diagnose());ipcMain.handle('connection:copy',()=>{const url=connection.snapshot().connectionUrl;if(!url)throw new Error('URL MCP chưa sẵn sàng.');clipboard.writeText(url);return true});ipcMain.handle('connection:rotate',()=>connection.rotate());ipcMain.handle('connection:copy-diagnostic',async()=>{const d=await connection.diagnose();clipboard.writeText(connection.report(d));return true});
ipcMain.handle('usage:snapshot',(_,days)=>usage.snapshot(days));ipcMain.handle('usage:clear',()=>usage.clear());ipcMain.handle('settings:get',()=>store.settings());ipcMain.handle('settings:update',(_,s)=>saveSettings(s));ipcMain.handle('app:info',()=>({version:app.getVersion(),platform:process.platform,port:PORT,packaged:app.isPackaged}));ipcMain.handle('app:hide',()=>{mainWindow?.hide();return true});
if(gotLock){app.on('second-instance',showWindow);app.whenReady().then(async()=>{if(process.platform==='win32')app.setAppUserModelId('com.personal.chatcode');Menu.setApplicationMenu(null);const s=store.ensure();applyLogin(s.settings.launchAtLogin);createTray();createWindow(!process.argv.includes('--background'));await projects.initialize();try{await ensureMcpServer();connection.start({fromWatchdog:true}).catch(()=>{})}catch(e){connectionChanged({...connection.snapshot(),status:'local-error',error:String(e.message||e)})}connection.restartWatchdog();powerMonitor.on('resume',()=>connection.resume());app.on('activate',showWindow)})}
app.on('before-quit',()=>{isQuitting=true;projects.shutdown();connection.shutdown();resetMcpServer().catch(()=>{})});app.on('window-all-closed',()=>{const s=store.read().settings;if(!s.closeToTray||(process.platform==='darwin'&&!tray))app.quit()});
