const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const dns = require('dns').promises;
const { spawn, execFile } = require('child_process');
const crypto = require('crypto');

const BACKOFF=[2000,5000,10000,30000,60000];
function createConnectionService({app,safeStorage,store,port,ensureMcpServer,resetMcpServer,getMcpRuntime,onChanged}){
  let proc=null,intentionalStop=false,reconnectTimer=null,watchdogTimer=null,reconnectAttempt=0,quitting=false;
  let tunnel={status:'stopped',publicBaseUrl:'',error:'',mode:'custom'};
  const health={localOk:false,publicOk:false,localMs:0,publicMs:0,lastCheckAt:'',consecutiveFailures:0,reconnectCount:0,lastReconnectAt:'',lastDisconnectReason:'',nextRetryAt:'',lastCloudflaredError:''};
  const notify=()=>onChanged?.(snapshot());
  const extractToken=value=>{const text=String(value||'').trim();if(!text)return'';return(text.match(/--token\s+([A-Za-z0-9._=\-]+)/i)?.[1]||text.match(/service\s+install\s+([A-Za-z0-9._=\-]+)/i)?.[1]||text).trim()};
  function encrypt(value){if(!safeStorage.isEncryptionAvailable())throw new Error('Windows Secure Storage chưa sẵn sàng để lưu Tunnel Token.');return safeStorage.encryptString(String(value)).toString('base64')}
  function decrypt(value){if(!value)return'';if(!safeStorage.isEncryptionAvailable())throw new Error('Windows Secure Storage chưa sẵn sàng để đọc Tunnel Token.');return safeStorage.decryptString(Buffer.from(value,'base64'))}
  function snapshot(){const cfg=store.connectionConfig(),runtime=getMcpRuntime();return{...cfg,status:tunnel.status,error:tunnel.error,localUrl:runtime?.localUrl||'',publicBaseUrl:tunnel.publicBaseUrl||'',connectionUrl:tunnel.publicBaseUrl&&runtime?`${tunnel.publicBaseUrl}${runtime.route}`:'',uptimeSec:Math.floor(process.uptime()),health:{...health},watchdog:{autoReconnect:store.read().settings.autoReconnect,reconnectAttempt}}}
  const clearRetry=()=>{if(reconnectTimer){clearTimeout(reconnectTimer);reconnectTimer=null}health.nextRetryAt=''};
  function schedule(reason='Mất kết nối'){const s=store.read();if(quitting||intentionalStop||!s.settings.autoReconnect)return;if(s.connection.mode==='custom'&&(!s.connection.domain||!s.connection.tunnelTokenEnc))return;if(reconnectTimer)return;const delay=BACKOFF[Math.min(reconnectAttempt,BACKOFF.length-1)];reconnectAttempt++;health.lastDisconnectReason=String(reason).slice(0,500);health.nextRetryAt=new Date(Date.now()+delay).toISOString();tunnel={...tunnel,status:'reconnecting',error:health.lastDisconnectReason};notify();reconnectTimer=setTimeout(async()=>{reconnectTimer=null;health.nextRetryAt='';health.reconnectCount++;health.lastReconnectAt=new Date().toISOString();try{await start({fromWatchdog:true})}catch(e){schedule(e.message||e)}},delay)}
  async function stop({intentional=true}={}){if(intentional){intentionalStop=true;clearRetry()}if(proc&&!proc.killed){proc.__chatcodeIntentional=true;try{proc.kill()}catch{}}proc=null;tunnel={status:'stopped',publicBaseUrl:'',error:'',mode:store.read().connection.mode};notify();return snapshot()}
  async function cloudflared(){const {install}=await import('cloudflared');const dir=path.join(app.getPath('userData'),'bin');await fsp.mkdir(dir,{recursive:true});const bin=path.join(dir,process.platform==='win32'?'cloudflared.exe':'cloudflared');if(!fs.existsSync(bin)){tunnel.status='installing-tunnel';notify();await install(bin)}return bin}
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  async function probe(url,timeout=4500){const started=Date.now();try{const res=await fetch(`${url}${url.includes('?')?'&':'?'}t=${Date.now()}`,{headers:{'cache-control':'no-cache'},signal:AbortSignal.timeout(timeout)}),body=await res.json().catch(()=>null);return{ok:res.ok&&body?.ok&&body?.service==='personal-chatcode',status:res.status,ms:Date.now()-started,detail:body}}catch(e){return{ok:false,status:0,ms:Date.now()-started,error:String(e.message||e)}}}
  async function waitPublic(base,p,timeout=35000){const started=Date.now();let last='';while(Date.now()-started<timeout){if(p.exitCode!==null)throw new Error(`Cloudflare Tunnel đã dừng (mã ${p.exitCode}).`);const r=await probe(`${base}/health`,4000);if(r.ok)return;last=r.error||`HTTP ${r.status}`;await sleep(1000)}throw new Error(`Không thể truy cập ${base}/health. ${last}`)}
  function bind(p,mode){proc=p;p.stderr?.on('data',chunk=>{const line=String(chunk||'').split(/\r?\n/).find(x=>/ERR|error/i.test(x));if(line)health.lastCloudflaredError=line.slice(0,700)});p.on('error',err=>{const reason=String(err.message||err);health.lastDisconnectReason=reason;tunnel={status:'tunnel-error',publicBaseUrl:'',error:reason,mode};notify();schedule(reason)});p.on('exit',code=>{if(proc===p)proc=null;if(quitting||intentionalStop||p.__chatcodeIntentional)return;const reason=health.lastCloudflaredError||`Cloudflare Tunnel đã dừng (${code??'không rõ mã'}).`;health.lastDisconnectReason=reason;tunnel={status:'tunnel-error',publicBaseUrl:'',error:reason,mode};notify();schedule(reason)})}
  async function quick(bin){return new Promise((resolve,reject)=>{let settled=false;const p=spawn(bin,['tunnel','--no-autoupdate','--url',`http://127.0.0.1:${port}`],{windowsHide:true,stdio:['ignore','pipe','pipe']});bind(p,'quick');const onData=async chunk=>{const match=String(chunk||'').match(/https:\/\/[a-z0-9-]+\.trycloudflare\.com/i);if(!match||settled)return;settled=true;try{tunnel={status:'verifying',publicBaseUrl:match[0],error:'',mode:'quick'};notify();await waitPublic(match[0],p,25000);tunnel={status:'connected',publicBaseUrl:match[0],error:'',mode:'quick'};reconnectAttempt=0;notify();resolve(snapshot())}catch(e){try{p.kill()}catch{}reject(e)}};p.stdout.on('data',onData);p.stderr.on('data',onData);setTimeout(()=>{if(!settled){settled=true;try{p.kill()}catch{}reject(new Error('Hết thời gian chờ Quick Tunnel.'))}},45000)})}
  async function custom(bin,state){const domain=store.normalizeDomain(state.connection.domain),token=decrypt(state.connection.tunnelTokenEnc);if(!domain||!token)throw new Error('Hãy nhập Domain và Tunnel Token trước khi kết nối.');const base=`https://${domain}`,p=spawn(bin,['tunnel','run','--token',token],{windowsHide:true,stdio:['ignore','pipe','pipe']});bind(p,'custom');tunnel={status:'verifying',publicBaseUrl:base,error:'',mode:'custom'};notify();try{await waitPublic(base,p,35000);tunnel={status:'connected',publicBaseUrl:base,error:'',mode:'custom'};reconnectAttempt=0;health.consecutiveFailures=0;notify();return snapshot()}catch(e){try{p.kill()}catch{}throw e}}
  async function start({fromWatchdog=false}={}){await ensureMcpServer();if(!fromWatchdog)clearRetry();intentionalStop=false;if(proc&&!proc.killed){proc.__chatcodeIntentional=true;try{proc.kill()}catch{}}proc=null;const s=store.ensure(),mode=s.connection.mode;if(mode==='custom'&&(!s.connection.domain||!s.connection.tunnelTokenEnc)){tunnel={status:'config-required',publicBaseUrl:'',error:'',mode};notify();return snapshot()}tunnel={status:fromWatchdog?'reconnecting':'starting',publicBaseUrl:'',error:'',mode};notify();try{const bin=await cloudflared();return mode==='quick'?await quick(bin):await custom(bin,s)}catch(e){const msg=String(e.message||e);health.lastDisconnectReason=msg;tunnel={status:'tunnel-error',publicBaseUrl:'',error:msg,mode};notify();if(fromWatchdog||s.settings.autoReconnect)schedule(msg);throw e}}
  async function watchdogCheck(){if(quitting)return;const local=await probe(`http://127.0.0.1:${port}/health`,3000);health.localOk=local.ok;health.localMs=local.ms;health.lastCheckAt=new Date().toISOString();if(!local.ok){health.publicOk=false;health.consecutiveFailures++;tunnel={...tunnel,status:'local-error',error:'Local MCP health check thất bại.'};notify();try{await resetMcpServer();await ensureMcpServer()}catch{}return}if(tunnel.publicBaseUrl){const pub=await probe(`${tunnel.publicBaseUrl}/health`,4500);health.publicOk=pub.ok;health.publicMs=pub.ms;if(pub.ok){health.consecutiveFailures=0;if(tunnel.status!=='connected'&&proc){tunnel.status='connected';tunnel.error='';notify()}}else{health.consecutiveFailures++;if(health.consecutiveFailures>=2&&!intentionalStop){const reason=pub.error||`Public health HTTP ${pub.status}`;health.lastDisconnectReason=reason;tunnel={...tunnel,status:'offline',error:reason};notify();if(proc&&!proc.killed)try{proc.kill()}catch{}schedule(reason)}}}else health.publicOk=false;notify()}
  function restartWatchdog(){if(watchdogTimer){clearInterval(watchdogTimer);watchdogTimer=null}watchdogTimer=setInterval(()=>watchdogCheck().catch(()=>{}),store.read().settings.healthIntervalSec*1000);setTimeout(()=>watchdogCheck().catch(()=>{}),1500)}
  async function saveConfig(incoming={}){await stop({intentional:true});const s=store.read(),mode=incoming.mode==='quick'?'quick':'custom';s.connection.mode=mode;if(mode==='custom'){s.connection.domain=store.normalizeDomain(incoming.domain);const token=extractToken(incoming.tunnelToken);if(token)s.connection.tunnelTokenEnc=encrypt(token);if(!s.connection.domain)throw new Error('Vui lòng nhập domain Cloudflare.');if(!s.connection.tunnelTokenEnc)throw new Error('Vui lòng nhập Tunnel Token/Key của Cloudflare.')}store.write(s);return store.connectionConfig(s)}
  async function clearToken(){await stop({intentional:true});const s=store.read();s.connection.tunnelTokenEnc='';store.write(s);tunnel={status:'config-required',publicBaseUrl:'',error:'',mode:s.connection.mode};notify();return store.connectionConfig(s)}
  async function rotate(){await stop({intentional:true});await resetMcpServer();const s=store.read();s.connection.token=crypto.randomBytes(24).toString('hex');store.write(s);await ensureMcpServer();return start()}
  function runExec(command,args,cwd,timeout=10000){return new Promise(resolve=>execFile(command,args,{cwd,timeout,windowsHide:true,maxBuffer:1024*1024},(error,stdout,stderr)=>resolve({ok:!error,stdout:String(stdout||''),stderr:String(stderr||error?.message||'')})))}
  async function diagnose(){await ensureMcpServer();const snap=snapshot(),checks=[];async function check(name,fn){const started=Date.now();try{const detail=await fn();checks.push({name,ok:true,ms:Date.now()-started,detail:String(detail||'OK').slice(0,700)})}catch(e){checks.push({name,ok:false,ms:Date.now()-started,detail:String(e.message||e).slice(0,700)})}}await check('Local MCP',async()=>{const r=await probe(`http://127.0.0.1:${port}/health`,4000);if(!r.ok)throw new Error(r.error||`HTTP ${r.status}`);return`OK · ${r.ms} ms`});if(snap.domain)await check('DNS domain',async()=>{const a=await dns.resolve4(snap.domain);return a.join(', ')});if(snap.publicBaseUrl)await check('Cloudflare HTTPS',async()=>{const r=await probe(`${snap.publicBaseUrl}/health`,6000);if(!r.ok)throw new Error(r.error||`HTTP ${r.status}`);return`OK · ${r.ms} ms`});if(snap.connectionUrl){const call=async body=>{const res=await fetch(snap.connectionUrl,{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream'},body:JSON.stringify(body),signal:AbortSignal.timeout(8000)}),text=await res.text();if(!res.ok)throw new Error(`HTTP ${res.status}: ${text.slice(0,300)}`);return text};await check('MCP initialize',()=>call({jsonrpc:'2.0',id:901,method:'initialize',params:{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'chatcode-self-test',version:app.getVersion()}}}));await check('MCP tools/list',()=>call({jsonrpc:'2.0',id:902,method:'tools/list',params:{}}))}try{const bin=await cloudflared();await check('cloudflared',async()=>{const r=await runExec(bin,['--version'],app.getPath('userData'));if(!r.ok)throw new Error(r.stderr);return r.stdout.trim()})}catch{}return{ok:checks.every(x=>x.ok),checks,snapshot:{status:snap.status,domain:snap.domain,mode:snap.mode,health:snap.health,watchdog:snap.watchdog,version:app.getVersion(),projectCount:store.read().projects.length}}}
  const report=diag=>JSON.stringify({generatedAt:new Date().toISOString(),app:'ChatCode Cá Nhân',version:app.getVersion(),platform:process.platform,...diag},null,2);
  function resume(){watchdogCheck().catch(()=>{});if(store.read().settings.autoReconnect&&tunnel.status!=='connected')schedule('Máy vừa resume')}
  function shutdown(){quitting=true;clearRetry();if(watchdogTimer)clearInterval(watchdogTimer);if(proc&&!proc.killed){proc.__chatcodeIntentional=true;try{proc.kill()}catch{}}}
  return{snapshot,start,stop,saveConfig,clearToken,rotate,diagnose,report,restartWatchdog,resume,shutdown};
}
module.exports={createConnectionService};
